wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.33.0
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.12
    start_time: 1711526306
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      4: 3.10.12
      5: 0.12.9
      6: 4.33.0
      8:
      - 1
      - 2
      - 5
