wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.33.0
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1711526557.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 103
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.5
      6: 4.33.0
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
